import Head from "next/head";

export default function Home({ prefix }) {
  console.log("Path is" + prefix);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${prefix}/favicon.ico`} />
      </Head>

      <main>
        <h4>hello my beautiful world!</h4>
        <a href={`${prefix}/about`}>About Page</a>
        <p>What's up my dude</p>
        <p>Let's say goodbye</p>
        <img src={`${prefix}/favicon.ico`} alt="hey" />
      </main>
    </>
  );
}
